### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit.runtime.in_memory_file_manager'

### ISSUE THREAD

**Issue by ffdown** [osi1880vr/ai-pixel-dreamer#4]
Traceback (most recent call last):
  File "e:\Anaconda3\envs\aidreamer\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "E:\AI\SD\ai-pixel-dreamer-main\scripts\webui_streamlit.py", line 126, in <module>
    layout()
  File "E:\AI\SD\ai-pixel-dreamer-main\scripts\webui_streamlit.py", line 99, in layout
    pluginModule = importlib.import_module(f"scripts.ui.{plugin[:-3]}")
  File "e:\Anaconda3\envs\aidreamer\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\AI\SD\ai-pixel-dreamer-main\scripts\ui\imglab.py", line 9, in <module>
    from streamlit.runtime.in_memory_file_manager import in_memory_file_manager
ModuleNotFoundError: No module named 'streamlit.runtime.in_memory_file_manager'

**Comment by osi1880vr** [comment]
please test again, I did some updates which schould fix the issue

**Comment by ffdown** [comment]
Nice. Thanks!
